"use client";

import { useEffect, useRef, useState } from "react";
import { Check, Copy, Sparkles } from "lucide-react";
import type { Incident } from "@/mock/incident";

/** Streams a scripted root-cause analysis for the incident; copyable as markdown. */
export function IncidentRca({ incident }: { incident: Incident }) {
  const [started, setStarted] = useState(false);
  const [chars, setChars] = useState(0);
  const [copied, setCopied] = useState(false);
  const raf = useRef<number | null>(null);

  const sections = incident.rca;
  const totalChars = sections.reduce((s, x) => s + x.body.length, 0);
  const done = chars >= totalChars;

  useEffect(() => {
    if (!started) return;
    const reduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    if (reduced) {
      setChars(totalChars);
      return;
    }
    let last = performance.now();
    const tick = (now: number) => {
      const dt = now - last;
      last = now;
      setChars((c) => Math.min(totalChars, c + dt * 1.3));
      raf.current = requestAnimationFrame(tick);
    };
    raf.current = requestAnimationFrame(tick);
    return () => {
      if (raf.current) cancelAnimationFrame(raf.current);
    };
  }, [started, totalChars]);

  useEffect(() => {
    if (done && raf.current) cancelAnimationFrame(raf.current);
  }, [done]);

  const copyMarkdown = () => {
    const md = [
      `# ${incident.id} — ${incident.title}`,
      ``,
      `**Window:** ${incident.started} → ${incident.ended} (${incident.duration}) · **Status:** ${incident.status}`,
      `**Impact:** ${incident.impact}`,
      ``,
      ...sections.flatMap((s) => [`## ${s.heading}`, ``, s.body, ``]),
      `---`,
      `Generated by obstack from correlated pipelines, alerts, K8s events, metrics and traces.`,
    ].join("\n");
    navigator.clipboard.writeText(md).catch(() => {});
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  let budget = Math.floor(chars);
  const rendered = sections.map((s) => {
    const take = Math.max(0, Math.min(s.body.length, budget));
    budget -= s.body.length;
    return { ...s, visible: s.body.slice(0, take), active: take > 0 && take < s.body.length };
  });

  if (!started) {
    return (
      <button
        type="button"
        onClick={() => setStarted(true)}
        className="mt-4 flex w-full items-center justify-center gap-2 rounded-lg border py-3 text-[13.5px] font-medium transition-colors"
        style={{
          color: "var(--color-llm)",
          borderColor: "color-mix(in srgb, var(--color-llm) 40%, var(--color-line))",
          background: "color-mix(in srgb, var(--color-llm) 6%, transparent)",
        }}
      >
        <Sparkles className="h-4 w-4" />
        Generate root-cause analysis
        <span className="font-mono text-[10px] uppercase tracking-widest opacity-70">ai assist</span>
      </button>
    );
  }

  return (
    <div
      className="mt-4 rounded-lg border bg-raised"
      style={{ borderColor: "color-mix(in srgb, var(--color-llm) 35%, var(--color-line))" }}
    >
      <div className="flex items-center justify-between border-b border-line px-3.5 py-2">
        <span className="flex items-center gap-2 font-mono text-[11px] uppercase tracking-widest" style={{ color: "var(--color-llm)" }}>
          <Sparkles className="h-3.5 w-3.5" />
          root-cause analysis
          {!done && <span className="pulse-dot text-faint">reading the timeline…</span>}
        </span>
        {done && (
          <button
            type="button"
            onClick={copyMarkdown}
            className="flex items-center gap-1.5 rounded-md border border-line bg-surface px-2 py-1 font-mono text-[10.5px] text-mid hover:border-line-strong hover:text-ink"
          >
            {copied ? (
              <Check className="h-3 w-3" style={{ color: "var(--color-ok)" }} />
            ) : (
              <Copy className="h-3 w-3" />
            )}
            {copied ? "copied" : "copy as markdown"}
          </button>
        )}
      </div>
      <div className="space-y-3.5 px-4 py-3.5">
        {rendered.map((s) =>
          s.visible.length === 0 ? null : (
            <div key={s.heading}>
              <p className="mb-0.5 font-mono text-[9.5px] uppercase tracking-widest text-faint">
                {s.heading}
              </p>
              <p className="text-[13px] leading-relaxed text-mid">
                {s.visible}
                {s.active && (
                  <span
                    className="ml-px inline-block h-3 w-[6px] animate-pulse align-middle"
                    style={{ background: "var(--color-llm)" }}
                  />
                )}
              </p>
            </div>
          ),
        )}
      </div>
      {done && (
        <p className="border-t border-line px-4 py-2 font-mono text-[10px] leading-relaxed text-faint">
          generated from the correlated timeline above — pipelines, alerts, k8s events, metrics and
          traces. Review before publishing; this is a draft, not a verdict.
        </p>
      )}
    </div>
  );
}
