import "server-only";
import { getAuth } from "@/server/auth";
import type { QueryRows } from "@/server/postgres";

/**
 * Invitations, as server-side calls into better-auth's organization plugin
 * (D143). ZERO doors open for them: `ALLOWED_ENDPOINTS` in
 * `app/api/auth/[...all]/route.ts` stays `{get-session, sign-out}` and the five
 * invitation HTTP paths join the D120 matrix as named STAY-CLOSED entries.
 * Everything below reaches `auth.api.*` in-process with the request's own
 * headers — the same shape the signup and login actions use — which is what
 * lets THIS module own the invariant the raw endpoints would break.
 *
 * The invariant is the owner pin (D148): an org id is always the caller's
 * `SessionContext.orgId`, resolved on the server, and never a value a caller
 * supplied. better-auth would happily take `organizationId` off a request body
 * and answer for whatever org the caller happens to be a member of; every
 * function here takes the org as a parameter its caller filled from the session.
 *
 * The other half — acceptance is ADDITIVE, never a re-home — is not enforced
 * here at all, and that is deliberate. `acceptInvitation` writes the invitee's
 * session row `activeOrganizationId` to the INVITING org (measured at 1.7.1,
 * `crud-invites.mjs:330`), and `resolveSessionContext` does not read that column:
 * it resolves through the `member` row the user OWNS (`session.ts:26-32`). So an
 * accepted invitation adds a membership and moves nothing. Proven both ways in
 * `invites.integration.test.ts`, against real rows.
 */

/** The only role this product invites at: D148 leaves member removal and role changes out. */
export const INVITE_ROLE = "member";

/**
 * The copyable link (D143's U4 answer — no email is sent). One definition: the
 * Members tab builds a link with this, and `app/invite/[id]` is the route that
 * answers it. The invitation id IS the token; no second token table exists.
 */
export const inviteLinkPath = (invitationId: string): string => `/invite/${invitationId}`;

/**
 * The id shape, as a total parse (D68). An invitation id arrives off a URL path
 * segment or a form field, so it may be absent, repeated, empty, 5000 characters
 * or `%00`-laced, and this is the only thing between it and a bound parameter.
 *
 * Measured at better-auth 1.7.1: the id is 32 characters from `[a-zA-Z0-9]`
 * (`@better-auth/core/dist/utils/id.mjs` — `createRandomStringGenerator("a-z",
 * "A-Z", "0-9")(32)`), and the invitation row's id is generated by that path.
 * The bound here is deliberately looser than 32 and still finite: a library that
 * lengthens its ids keeps working, and nothing outside the alphabet — including
 * every hostile value in the D68 corpus that is not a plain alphanumeric word —
 * ever reaches Postgres or a URL this app writes.
 *
 * Prototype names (`toString`, `constructor`, `__proto__`) are judged by that
 * rule and nothing else: `toString` is a syntactically valid id and comes back
 * as one, which is safe because an id is only ever BOUND as `$1` or compared,
 * never used for a property lookup. `__proto__` carries underscores and is
 * refused by the alphabet.
 */
const INVITATION_ID = /^[A-Za-z0-9]{1,64}$/;

export function parseInvitationId(raw: string | string[] | undefined): string | null {
  if (raw === undefined) return null;
  const value = Array.isArray(raw) ? raw[0] : raw;
  if (typeof value !== "string") return null;
  return INVITATION_ID.test(value) ? value : null;
}

/** A pending invitation, as the Members tab shows it. */
export interface PendingInvite {
  id: string;
  email: string;
  expiresAt: Date;
}

/** A member of the org, as the Members tab shows them. */
export interface OrgMember {
  userId: string;
  name: string;
  email: string;
  role: string;
}

/** What the accept surface knows about an invitation it may still accept. */
export interface InviteForRecipient {
  id: string;
  email: string;
  organizationName: string;
}

/** better-auth returns its own row shape; this is the half the product shows. */
type LibraryInvitation = {
  id: string;
  email: string;
  status: string;
  expiresAt: Date;
};

const toPendingInvite = (invitation: LibraryInvitation): PendingInvite => ({
  id: invitation.id,
  email: invitation.email,
  expiresAt: new Date(invitation.expiresAt),
});

/**
 * Invite `email` into `orgId` as a member, and hand back the row the copyable
 * link is built from.
 *
 * `organizationId` is passed explicitly rather than left to better-auth's
 * fallback: its default is the session row's `activeOrganizationId`
 * (`crud-invites.mjs:85`), which acceptance moves (see the module note), so a
 * user who has accepted someone else's invitation would otherwise invite into
 * THEIR org. The caller's owner-pinned org is the only correct answer.
 */
export async function createInvite(
  orgId: string,
  email: string,
  requestHeaders: Headers,
): Promise<PendingInvite> {
  const invitation = (await getAuth().api.createInvitation({
    body: { email, role: INVITE_ROLE, organizationId: orgId },
    headers: requestHeaders,
  })) as LibraryInvitation;
  return toPendingInvite(invitation);
}

/**
 * The org's invitations that are still open. better-auth's `listInvitations`
 * returns every status it has ever held (`adapter.mjs:784` filters on
 * organizationId alone), and an expired row is not a link anyone can use, so
 * both are filtered here rather than shown as pending.
 */
export async function listPendingInvites(
  orgId: string,
  requestHeaders: Headers,
): Promise<PendingInvite[]> {
  const invitations = (await getAuth().api.listInvitations({
    query: { organizationId: orgId },
    headers: requestHeaders,
  })) as LibraryInvitation[];
  const now = Date.now();
  return invitations
    .filter((i) => i.status === "pending" && new Date(i.expiresAt).getTime() > now)
    .map(toPendingInvite);
}

/**
 * Cancel one of THIS org's pending invitations.
 *
 * The membership check is ours, before the library's. better-auth's
 * `cancelInvitation` resolves the org from the invitation row and then asks
 * whether the caller may cancel in THAT org (`crud-invites.mjs:428-440`) — which
 * is a correct check about a different question. D148 fixes the question: an
 * action operates on the caller's own org, so an invitation id that is not this
 * org's is refused here and never reaches the library.
 */
export async function cancelInvite(
  orgId: string,
  invitationId: string,
  requestHeaders: Headers,
): Promise<void> {
  const pending = await listPendingInvites(orgId, requestHeaders);
  if (!pending.some((invite) => invite.id === invitationId)) {
    throw new Error("that invitation does not belong to this workspace's organization");
  }
  await getAuth().api.cancelInvitation({
    body: { invitationId },
    headers: requestHeaders,
  });
}

/**
 * The invitation as its RECIPIENT may see it, or a throw.
 *
 * Every guard is better-auth's own (`crud-invites.mjs:498-522`): it needs a
 * session, the invitation must still be pending and unexpired, and the signed-in
 * user's email must equal the invited one case-insensitively. This module adds
 * nothing — the link is a bearer token, and the library's recipient check is the
 * thing that keeps it from being one anybody can spend.
 */
export async function getInviteForRecipient(
  invitationId: string,
  requestHeaders: Headers,
): Promise<InviteForRecipient> {
  const invitation = (await getAuth().api.getInvitation({
    query: { id: invitationId },
    headers: requestHeaders,
  })) as { id: string; email: string; organizationName: string };
  return {
    id: invitation.id,
    email: invitation.email,
    organizationName: invitation.organizationName,
  };
}

/**
 * Accept it. Additive by construction — see the module note: the member row is
 * the whole effect the product reads, and the `activeOrganizationId` write that
 * comes with it is a column no resolution in this repo looks at.
 */
export async function acceptInvite(
  invitationId: string,
  requestHeaders: Headers,
): Promise<void> {
  await getAuth().api.acceptInvitation({
    body: { invitationId },
    headers: requestHeaders,
  });
}

/**
 * The org's roster. Plain SQL rather than `auth.api.listMembers`, because that
 * would be a SIXTH invitation-adjacent endpoint in a sprint whose ruling names
 * exactly five (D143) — and a roster is a read of two tables this repo already
 * reads. The org is a bound parameter (D11) and comes from the session.
 */
const MEMBERS_SQL = `
  SELECT m."userId" AS user_id, m.role, u.name, u.email
    FROM "member" m
    JOIN "user" u ON u.id = m."userId"
   WHERE m."organizationId" = $1
   ORDER BY m."createdAt", m.id`;

export async function listOrgMembers(orgId: string, query: QueryRows): Promise<OrgMember[]> {
  const rows = await query<{ user_id: string; role: string; name: string; email: string }>(
    MEMBERS_SQL,
    [orgId],
  );
  return rows.map((row) => ({
    userId: row.user_id,
    name: row.name,
    email: row.email,
    role: row.role,
  }));
}

/**
 * The org's display name — the settings surface's heading, and null when no such
 * row exists (its caller decides what a missing organization means).
 *
 * Plain SQL for the same reason `listOrgMembers` is (D143): the sprint's
 * endpoint ruling names five invitation endpoints, and reaching for a sixth
 * `auth.api.*` call to read one column of a table this repo already reads would
 * widen the surface for nothing. It lives HERE rather than at the page that
 * shows it because SQL has one home in this app (D158) — `src/server` — and the
 * org read surface is this module.
 */
const ORG_NAME_SQL = `SELECT name FROM "organization" WHERE id = $1`;

export async function getOrgName(orgId: string, query: QueryRows): Promise<string | null> {
  const [row] = await query<{ name: string }>(ORG_NAME_SQL, [orgId]);
  return row?.name ?? null;
}

/**
 * The org this viewer joined through this invitation, if they did — the
 * accept-success surface's fact.
 *
 * It exists because better-auth cannot answer it: once an invitation is
 * accepted, `getInvitation` refuses it as "not found" (`crud-invites.mjs:503`
 * requires `status === "pending"`), so a person who has just joined and a person
 * holding a cancelled link are indistinguishable through the library. Without
 * this, reopening the link one second after joining would say the link is dead.
 *
 * It discloses nothing: the row only exists when the invitation was addressed to
 * the ASKING user's email AND they are already a member of that org, both bound
 * as parameters. A stranger holding the id gets null, exactly as before.
 */
const JOINED_ORG_SQL = `
  SELECT o.name AS org_name
    FROM "invitation" i
    JOIN "organization" o ON o.id = i."organizationId"
    JOIN "member" m ON m."organizationId" = i."organizationId" AND m."userId" = $2
   WHERE i.id = $1 AND i.status = 'accepted' AND lower(i.email) = lower($3)`;

export async function findJoinedOrgName(
  invitationId: string,
  userId: string,
  userEmail: string,
  query: QueryRows,
): Promise<string | null> {
  const [row] = await query<{ org_name: string }>(JOINED_ORG_SQL, [
    invitationId,
    userId,
    userEmail,
  ]);
  return row?.org_name ?? null;
}
