apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ingest
  labels:
    {{- include "obstack.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingest
spec:
  selector:
    app.kubernetes.io/name: obstack
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ingest
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
    - name: admin
      port: 8080
      targetPort: admin
