apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-clickhouse
  labels:
    {{- include "obstack.labels" . | nindent 4 }}
    app.kubernetes.io/component: clickhouse
spec:
  selector:
    app.kubernetes.io/name: obstack
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: clickhouse
  ports:
    - name: http
      port: 8123
      targetPort: http
    - name: native
      port: 9000
      targetPort: native
